---
- name: Include OS-specific variables for {{ ansible_os_family }}.
  include_vars: "{{ ansible_os_family }}.yml"

- name: set facts for playbook execution
  set_fact:
    elasticsearch_checksum: "{{ lookup('url', elasticsearch_package_sha512) }}"

- name: assert minimun number of cluster expected nodes are present
  assert:
    that:
      - "{{ groups[elasticsearch_inventory_group] | length | int }} >= elasticsearch_cluster_expected_nodes"
    msg: "Mininum expected nodes verification for elasticsearch failed"
  register: mininum_expected_nodes

- name: Download elasticsearch package for {{ ansible_os_family }}
  get_url:
    url: "{{ elasticsearch_package_repository }}"
    dest: "{{ elasticsearch_package_path }}"
    force: yes
  when:
    - elasticsearch_package_repository is defined
    - elasticsearch_package_path is defined
    - mininum_expected_nodes is succeeded
  register: elasticsearch_package_downloaded

- name: calculate SHA512 for elasticsearch package
  stat:
    path: "{{ elasticsearch_package_path }}"
    checksum_algorithm: sha512
    get_checksum: yes
  register: elasticsearch_package_hash_sha512

- name: assert package checksum is secure
  assert:
    that:
      - "elasticsearch_package_hash_sha512.stat.checksum == '{{ elasticsearch_checksum.split(' ')[0] }}'"
    msg: "Elasticsearch package checksum verification failed"
  register: elasticsearch_checksum_verification

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure node using template file
- name: configure elasticsearch settings
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elastic/elasticsearch.yml
    force: yes
    mode: 0644
  vars:
    elasticsearch_unicast_inventory: "{{ groups[elasticsearch_inventory_group] | default(['127.0.0.1']) }}"
    node_master_enabled: "{{ hostvars[inventory_hostname].node_master }}"
    node_data_enabled: "{{ hostvars[inventory_hostname].node_data }}"
    node_client_enabled: "{{ hostvars[inventory_hostname].node_client }}"
  when: elasticsearch_installed is succeeded
  register: elasticsearch_settings

# Start service.
- name: Ensure elasticsearch is started and enabled to start at boot
  service: name=elasticsearch state=started enabled=yes
  when: elasticsearch_settings is succeeded